version: "3.8"

services:
  database:
    image: postgres
    container_name: git_clio_database
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: gitclio
      POSTGRES_USER: gitclio
      POSTGRES_DB: gitclio
  gitclio:
    build: .
    depends_on:
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database