object Dependencies {
    const val ktorCore = "io.ktor:ktor-client-core:${Versions.ktorVersion}"
    const val ktorAuth = "io.ktor:ktor-client-auth:${Versions.ktorVersion}"
    const val ktorCioEngine = "io.ktor:ktor-client-cio:${Versions.ktorVersion}"
    const val ktorClientLogging = "io.ktor:ktor-client-logging:${Versions.ktorVersion}"
    const val ktorContentNegotiation = "io.ktor:ktor-client-content-negotiation:${Versions.ktorVersion}"
    const val ktorKotlinxSerialization = "io.ktor:ktor-serialization-kotlinx-json:${Versions.ktorVersion}"
    const val koinCore = "io.insert-koin:koin-core:${Versions.koinCore}"
    const val koinKtor = "io.insert-koin:koin-ktor:${Versions.koinKtor}"
    const val koinKtorSl4jLogger = "io.insert-koin:koin-logger-slf4j:${Versions.koinKtor}"
    const val sl4jSimple = "org.slf4j:slf4j-simple:${Versions.sl4jSimple}"
    const val kotlinXDateTime = "org.jetbrains.kotlinx:kotlinx-datetime:${Versions.kotlinXDateTime}"
    const val exposedCore = "org.jetbrains.exposed:exposed-core:${Versions.exposedVersion}"
    const val exposedDao = "org.jetbrains.exposed:exposed-dao:${Versions.exposedVersion}"
    const val exposedJdbc = "org.jetbrains.exposed:exposed-jdbc:${Versions.exposedVersion}"
    const val exposedJavaTime = "org.jetbrains.exposed:exposed-java-time:${Versions.exposedVersion}"
    const val postgresql = "org.postgresql:postgresql:${Versions.postgresqlVersion}"
}
